import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { appCheck, firebaseApp } from "../lib/firebase";
import { FirebaseRecaptcha } from "../components/FirebaseRecaptcha";

const Home: NextPage = () => {
  console.log(appCheck, firebaseApp);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      hello
      <FirebaseRecaptcha></FirebaseRecaptcha>
      <main className={styles.main}>{JSON.stringify(appCheck)}</main>
    </div>
  );
};

export default Home;
